language: scala
scala:
    - "2.12.7"

jdk:
    - oraclejdk8

branches:
  only:
    - master
    - dev

# make sure sbt quartercask is build with master version
before_install:
  - git clone http://github.com/zeitgeist-project/zeitgeist-sbt ~/builds/zeitgeist-sbt
  - pushd ~/builds/zeitgeist-sbt
  - sbt compile publishLocal
  - popd
  - rm -rf ~/builds/zeitgeist-sbt

# build with coverage
script:
  - sbt clean coverage test coverageReport &&
    sbt coverageAggregate

# coveralls integration
after_success:
  - sbt coveralls

# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete